options:
  merge-default-rules: false
  severity: 2

rules:
  border-zero:
    - 2
    - convention: '0'

  brace-style:
    - 2
    - style: 2tbs
    - allow-single-line: false

  class-name-format:
    - 2

    # two conventions:
    # - in react components, use .ComponentName and .hasChildren, .isSelected, etc
    # - in cake CSS, use .module-name__child-name and .-modifier
    - convention: ^(([A-Z]|((is|are|has|should|can)[A-Z]))[a-zA-Z0-9]+$|[\-a-z][\-a-z0-9_]+$)
      ignore:
        - enter
        - enterActive
        - leave
        - leaveActive
        - appear
        - appearActive

  empty-line-between-blocks: 2

  function-name-format:
    - 2
    - convention: hyphenatedlowercase

  hex-notation:
    - 2
    - style: lowercase

  leading-zero:
    - 2
    - include: true

  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase

  nesting-depth:
    - 2
    - max-depth: 4

  no-color-literals:
    - 2
    - allow-rgba: true
    - allow-map-identifiers: true
    - allow-variable-identifiers: true

  no-debug:
    - 2

  no-duplicate-properties:
    - 2

  no-empty-rulesets:
    - 2

  no-extends:
    - 2

  no-ids:
    - 2

  no-invalid-hex:
    - 2

  no-qualifying-elements:
    - 2

  no-trailing-whitespace:
    - 2

  no-trailing-zero:
    - 2

  no-transition-all:
    - 2

  no-warn:
    - 2

  one-declaration-per-line:
    - 2

  property-sort-order:
    - 2
    - order: alphabetical

  quotes:
    - 2
    - style: single

  single-line-per-selector:
    - 2

  space-before-brace:
    - 2

  zero-unit:
    - 2
    - include: false
